name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Build version'
        required: true
    paths-ignore:
      - readme.md
      - README.md
      - CHANGELOG.md

  pull_request:
    branches:
      - master
      - develop


env:
  UI_BUILD_REACT: 'app/'
  BUILD_INFO_FILE: 'buildInfo.json'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Generate Build info
        run: |
          echo '{"build": { "version": "${{ github.event.inputs.version }}", "branch": "${{ github.sha }}", "build_date": "${{ env.BUILD_DATE }}", "name": "Service UI", "repo": "${{ github.repository }}"}}' > ./${{ env.UI_BUILD_REACT }}build/${{ env.BUILD_INFO_FILE }}
     
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12

     
      - name: JS Build
        env:
          NODE_OPTIONS: '--max_old_space_size=2048'

        run: |
          npm --prefix ${{ env.UI_BUILD_REACT }} ci
          npm --prefix ${{ env.UI_BUILD_REACT }} run lint
          npm --prefix ${{ env.UI_BUILD_REACT }} run test:coverage
          npm --prefix ${{ env.UI_BUILD_REACT }} run build

